// <auto-generated />
using System;
using BookCart.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookCart.Migrations
{
    [DbContext(typeof(BookDBContext))]
    partial class BookDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookCart.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CoverFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("BookId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Jon Skeet",
                            Category = "Programming",
                            CoverFileName = "csharp.jpg",
                            Price = 45.99m,
                            Title = "C# in Depth"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Robert C. Martin",
                            Category = "Programming",
                            CoverFileName = "cleancode.jpg",
                            Price = 39.99m,
                            Title = "Clean Code"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Andrew Hunt",
                            Category = "Programming",
                            CoverFileName = "pragprog.jpg",
                            Price = 42.50m,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Erich Gamma",
                            Category = "Programming",
                            CoverFileName = "designpatterns.jpg",
                            Price = 49.00m,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Thomas H. Cormen",
                            Category = "Computer Science",
                            CoverFileName = "algorithms.jpg",
                            Price = 59.99m,
                            Title = "Introduction to Algorithms"
                        });
                });

            modelBuilder.Entity("BookCart.Models.Cart", b =>
                {
                    b.Property<string>("CartId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CartId");

                    b.ToTable("Cart");

                    b.HasData(
                        new
                        {
                            CartId = "CART001",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            CartId = "CART002",
                            DateCreated = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            CartId = "CART003",
                            DateCreated = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            CartId = "CART004",
                            DateCreated = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            CartId = "CART005",
                            DateCreated = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BookCart.Models.CartItems", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId")
                        .HasName("PK__CartItem__488B0B0AA0297D1C");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            CartItemId = 1,
                            CartId = "CART001",
                            ProductId = 101,
                            Quantity = 2
                        },
                        new
                        {
                            CartItemId = 2,
                            CartId = "CART002",
                            ProductId = 102,
                            Quantity = 1
                        },
                        new
                        {
                            CartItemId = 3,
                            CartId = "CART003",
                            ProductId = 103,
                            Quantity = 3
                        },
                        new
                        {
                            CartItemId = 4,
                            CartId = "CART004",
                            ProductId = 104,
                            Quantity = 2
                        },
                        new
                        {
                            CartItemId = 5,
                            CartId = "CART005",
                            ProductId = 105,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("BookCart.Models.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A2B46B8DFC9");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Books"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Home & Kitchen"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Toys"
                        });
                });

            modelBuilder.Entity("BookCart.Models.CustomerOrderDetails", b =>
                {
                    b.Property<int>("OrderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailsId"));

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailsId")
                        .HasName("PK__Customer__9DD74DBD81D9221B");

                    b.ToTable("CustomerOrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailsId = 1,
                            OrderId = "ORD001",
                            Price = 199.99m,
                            ProductId = 101,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailsId = 2,
                            OrderId = "ORD001",
                            Price = 100.00m,
                            ProductId = 102,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailsId = 3,
                            OrderId = "ORD002",
                            Price = 75.25m,
                            ProductId = 103,
                            Quantity = 2
                        },
                        new
                        {
                            OrderDetailsId = 4,
                            OrderId = "ORD003",
                            Price = 75.75m,
                            ProductId = 104,
                            Quantity = 1
                        },
                        new
                        {
                            OrderDetailsId = 5,
                            OrderId = "ORD004",
                            Price = 105.05m,
                            ProductId = 105,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("BookCart.Models.CustomerOrders", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("CartTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("OrderId")
                        .HasName("PK__Customer__C3905BCF96C8F1E7");

                    b.ToTable("CustomerOrders");

                    b.HasData(
                        new
                        {
                            OrderId = "ORD001",
                            CartTotal = 299.99m,
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            OrderId = "ORD002",
                            CartTotal = 150.50m,
                            DateCreated = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            OrderId = "ORD003",
                            CartTotal = 75.75m,
                            DateCreated = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            OrderId = "ORD004",
                            CartTotal = 210.10m,
                            DateCreated = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            OrderId = "ORD005",
                            CartTotal = 500.00m,
                            DateCreated = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BookCart.Models.UserMaster", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__UserMast__1788CCAC2694A2ED");

                    b.ToTable("UserMaster");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FirstName = "John",
                            Gender = "Male",
                            LastName = "Doe",
                            Password = "Admin@123",
                            UserTypeId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            FirstName = "Jane",
                            Gender = "Female",
                            LastName = "Smith",
                            Password = "User@123",
                            UserTypeId = 2,
                            Username = "jane123"
                        },
                        new
                        {
                            UserId = 3,
                            FirstName = "Robert",
                            Gender = "Male",
                            LastName = "King",
                            Password = "Pass@123",
                            UserTypeId = 2,
                            Username = "robertK"
                        },
                        new
                        {
                            UserId = 4,
                            FirstName = "Emily",
                            Gender = "Female",
                            LastName = "Johnson",
                            Password = "Pass@123",
                            UserTypeId = 3,
                            Username = "emilyJ"
                        },
                        new
                        {
                            UserId = 5,
                            FirstName = "Michael",
                            Gender = "Male",
                            LastName = "Brown",
                            Password = "Pass@123",
                            UserTypeId = 4,
                            Username = "mikeB"
                        });
                });

            modelBuilder.Entity("BookCart.Models.UserType", b =>
                {
                    b.Property<int>("UserTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTypeId"));

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserTypeId");

                    b.ToTable("UserType");

                    b.HasData(
                        new
                        {
                            UserTypeId = 1,
                            UserTypeName = "Admin"
                        },
                        new
                        {
                            UserTypeId = 2,
                            UserTypeName = "User"
                        },
                        new
                        {
                            UserTypeId = 3,
                            UserTypeName = "Manager"
                        },
                        new
                        {
                            UserTypeId = 4,
                            UserTypeName = "Guest"
                        },
                        new
                        {
                            UserTypeId = 5,
                            UserTypeName = "Vendor"
                        });
                });

            modelBuilder.Entity("BookCart.Models.Wishlist", b =>
                {
                    b.Property<string>("WishlistId")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("WishlistId");

                    b.ToTable("Wishlist");

                    b.HasData(
                        new
                        {
                            WishlistId = "WISH001",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            WishlistId = "WISH002",
                            DateCreated = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            WishlistId = "WISH003",
                            DateCreated = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            WishlistId = "WISH004",
                            DateCreated = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            WishlistId = "WISH005",
                            DateCreated = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BookCart.Models.WishlistItems", b =>
                {
                    b.Property<int>("WishlistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistItemId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("WishlistId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)");

                    b.HasKey("WishlistItemId")
                        .HasName("PK__Wishlist__171E21A16A5148A4");

                    b.ToTable("WishlistItems");

                    b.HasData(
                        new
                        {
                            WishlistItemId = 1,
                            ProductId = 101,
                            WishlistId = "WISH001"
                        },
                        new
                        {
                            WishlistItemId = 2,
                            ProductId = 102,
                            WishlistId = "WISH002"
                        },
                        new
                        {
                            WishlistItemId = 3,
                            ProductId = 103,
                            WishlistId = "WISH003"
                        },
                        new
                        {
                            WishlistItemId = 4,
                            ProductId = 104,
                            WishlistId = "WISH004"
                        },
                        new
                        {
                            WishlistItemId = 5,
                            ProductId = 105,
                            WishlistId = "WISH005"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
